### ISSUE TITLE
Issue importing mediapipe on Raspberry Pi

### ISSUE THREAD

**Issue by assman** [jiuqiant/mediapipe_python_aarch64#1]
Hi

I followed the instructions and was successfully able to install mediapipe. When I run `ls /home/pi/.local/lib/python3.7/site-packages/mediapipe/python`, the solutions folder is present.

However, when I run the interactive python3 shell from my root directory and do a `import mediapipe as mp`, I get an error as such - 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/mediapipe/__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "/home/pi/.local/lib/python3.7/site-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: /home/pi/.local/lib/python3.7/site-packages/mediapipe/python/_framework_bindings.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_load_8
`

**Comment by vdlluca** [comment]
I'm experiencing the same problem but for the symbol "_ZN3ruy14Kernel8bitNeonERKNS_16KernelParams8bitILi4ELi2EEE"

**Comment by assman** [comment]
That's strange. I wonder what could be the issue that's causing this. Which OS are you on? I'm on raspbian.

**Comment by vdlluca** [comment]
I'm also on Raspbian (or Raspberry Pi OS what it's called now). I found the same [issue on the mediapipe repository] (https://github.com/google/mediapipe/issues/1346). My issue is related to Tensorflow. Your symbol however is one of the first in the binary. You can check with `nm -gCD /home/pi/.local/lib/python3.7/site-packages/mediapipe/python/_framework_bindings.cpython-37m-arm-linux-gnueabihf.so | grep -n "__atomic_load_8"`. My issure  Maybe your issue is related to cmake? I'm not sure.

**Comment by assman** [comment]
> I'm also on Raspbian (or Raspberry Pi OS what it's called now). I found the same issue on the mediapipe repository ([google/mediapipe#1346](https://github.com/google/mediapipe/issues/1346)). My issue is related to Tensorflow. Your symbol however is one of the first in the binary. You can check with `nm -gCD /home/pi/.local/lib/python3.7/site-packages/mediapipe/python/_framework_bindings.cpython-37m-arm-linux-gnueabihf.so | grep -n "__atomic_load_8"`. Maybe your issue is related to cmake? I'm not sure.

Ok I will check it out thank you

**Comment by vbartle** [comment]
Oh I had this problem with atomic, too, and found that building Bazel using the guide and scripts in [here](https://github.com/koenvervloesem/bazel-on-arm), then coming back and running the mediapipe installation fixed it.
